#!/usr/bin/env node
/**
 * Rewrites schemas/language.pack.schema.json from the station's own contract.
 *
 * A language entry's file is a console language pack: what the console's Settings, Languages exports
 * and what its import accepts. The station validates that with a zod schema generated from
 * apps/api/data/contracts/languages/languages.types.ck. This converts THAT schema rather than restating
 * it, so the catalogue refuses exactly what an import would. Run it against a deadair checkout whose
 * apps/api has its dependencies installed:
 *
 *     node scripts/language.schema.sync.mjs ../deadair
 *
 * and commit the result. Nothing runs it automatically, for persona.schema.sync.mjs's reason: the
 * catalogue must not depend on the station's repository being checked out beside it.
 *
 * The contract types the catalog as an open record, because only the console that loads a pack can
 * say whether each string fits its English. The shape rules the API applies on top (text only, the
 * size limits) are in catalog.rules.mjs.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const deadair = process.argv[2];
if (!deadair) {
    console.error('usage: node scripts/language.schema.sync.mjs <path to a deadair checkout>');
    process.exit(2);
}

const api = resolve(deadair, 'apps/api');
const types = join(api, 'src/modules/languages/types/languages.types.ts');
if (!existsSync(types)) {
    console.error(`no generated language types at ${types}`);
    process.exit(2);
}

// Evaluated with apps/api as the working directory so `zod` resolves to the version the station uses.
const program = `
import { z } from 'zod';
import { ConsoleLanguagePack } from ${JSON.stringify(types)};
process.stdout.write(JSON.stringify(z.toJSONSchema(ConsoleLanguagePack, { target: 'draft-2020-12' })));
`;
const schema = JSON.parse(execFileSync(process.execPath, ['--input-type=module', '--eval', program], { cwd: api, encoding: 'utf8' }));

const out = {
    $schema: schema.$schema,
    $id: 'https://robert-dean.github.io/deadair-community/schemas/language.pack.schema.json',
    $comment: 'Generated by scripts/language.schema.sync.mjs from the ConsoleLanguagePack contract in the deadair repository. Do not edit by hand.',
    title: 'Console language pack',
    ...Object.fromEntries(Object.entries(schema).filter(([key]) => key !== '$schema')),
};

writeFileSync(join(root, 'schemas/language.pack.schema.json'), JSON.stringify(out, null, 4) + '\n');
console.log('wrote schemas/language.pack.schema.json');
