#!/usr/bin/env node
/**
 * Rewrites schemas/persona.file.schema.json from the station's own contract.
 *
 * A persona entry's file is what the console exports and what its Import accepts, and the station
 * validates that with a zod schema generated from apps/api/data/contracts/personas/personas.types.ck.
 * This converts THAT schema rather than restating it, so the catalogue refuses exactly what an import
 * would. Run it against a deadair checkout whose apps/api has its dependencies installed:
 *
 *     node scripts/persona.schema.sync.mjs ../deadair
 *
 * and commit the result. Nothing runs it automatically, because the catalogue must not depend on the
 * station's repository being checked out beside it.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const deadair = process.argv[2];
if (!deadair) {
    console.error('usage: node scripts/persona.schema.sync.mjs <path to a deadair checkout>');
    process.exit(2);
}

const api = resolve(deadair, 'apps/api');
const types = join(api, 'src/modules/personas/types/personas.types.ts');
if (!existsSync(types)) {
    console.error(`no generated persona types at ${types}`);
    process.exit(2);
}

// Evaluated with apps/api as the working directory so `zod` resolves to the version the station uses.
const program = `
import { z } from 'zod';
import { PersonaFile } from ${JSON.stringify(types)};
process.stdout.write(JSON.stringify(z.toJSONSchema(PersonaFile, { target: 'draft-2020-12' })));
`;
const schema = JSON.parse(execFileSync(process.execPath, ['--input-type=module', '--eval', program], { cwd: api, encoding: 'utf8' }));

const out = {
    $schema: schema.$schema,
    $id: 'https://robert-dean.github.io/deadair-community/schemas/persona.file.schema.json',
    $comment: 'Generated by scripts/persona.schema.sync.mjs from the PersonaFile contract in the deadair repository. Do not edit by hand.',
    title: 'Persona file',
    ...Object.fromEntries(Object.entries(schema).filter(([key]) => key !== '$schema')),
};

writeFileSync(join(root, 'schemas/persona.file.schema.json'), JSON.stringify(out, null, 4) + '\n');
console.log('wrote schemas/persona.file.schema.json');
